name: skye_utils
description: A new Flutter Utils package of use Util
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
  flutter_smart_dialog: ^4.7.1
  responsive_builder: ^0.4.3
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  date_format: ^2.0.7
  path_provider: ^2.0.11
  logger: ^1.1.0
  event_bus: ^2.0.0
  sqflite: ^2.2.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  yaml: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  test: ^1.20.1
  source_gen_test: ^1.0.2
  analyzer: ^3.2.0
  build: ^2.2.1
  code_builder: ^4.1.0
  path: ^1.8.1
  source_gen: ^1.2.1
  freezed_annotation: ^1.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - resource/image/
    - resource/data/
    - resource/application.yaml
    - resource/sqlite_table.yaml
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
